name: Build and Test Go Application

# Triggers the workflow on separate events 
on:
  push:
    # Trigger the worflow on push event for all branches
    branches:
      -  '**'  
  pull_request:
    types: [opened, reopened, closed]
    branches: [main]
  pull_request_review_comment:
    types: [created, edited]
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notify on Slack For PR Opened or Closed
        # Only run this workflow when "build" workflow succeeds
        # needs: [build]
    
        # Only run this workflow if it target is main branch on pull_request event
        if: ${{ github.base_ref == 'main' && github.event_name == 'pull_request' && github.event.pull_request.state == 'open'}}
  
        uses: abinoda/slack-action@master
        env:
          # required
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          # custom message to send to slack
          args: '{\"channel\":\"${{ secrets.SLACK_PR_CHANNEL_ID }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pull Request:* ${{ github.event.pull_request.title }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Contributor :* ${{ github.event.pull_request.user.login }}\n*Request State:* ${{ github.event.pull_request.state }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<${{ github.event.pull_request.html_url }}|View Pull Request>\"}}]}' 
      - name: Notify on Slack For PR Comments
        # Only run this workflow if it target is main branch on pull_request_review_comment event
        if: ${{ github.base_ref == 'main' && github.event_name == 'pull_request' && github.event.pull_request.state == 'closed'}}
  
        uses: abinoda/slack-action@master
        env:
          # required
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          # custom message to send to slack
          args: '{\"channel\":\"${{ secrets.SLACK_PR_CHANNEL_ID }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pull Request Comment:* ${{ github.event.pull_request.title }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Contributor :* ${{ github.event.pull_request.user.login }}\n*Request State:* ${{ github.event.pull_request.state }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<${{ github.event.pull_request.html_url }}|View Pull Details>\"}}]}' 

